name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on push to main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use your specific Python version here

      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme  # Add any additional Sphinx extensions you may need

      - name: Build Documentation
        run: |
          # Change 'docs' to 'src/docs' to match your directory structure
          sphinx-build -b html src/docs/ build/  # Build HTML docs from the 'src/docs' directory

      - name: Upload Documentation to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # The 'build' directory should be the output directory from the Sphinx build command
          path: ./build
